####################################################
# BINARY SENSORS - CONTROL ROOM                    #
####################################################

  - platform: modbus
    scan_interval: 2
    inputs:
      - name: Water Valve Opened
        hub: MB_ControlRoom
        slave: 1
        address: 10
        
      - name: Water Valve Closed
        hub: MB_ControlRoom
        slave: 1
        address: 11
        
  - platform: template
    sensors:
      poweroutlet_status:
        friendly_name: Power Outlet
        entity_id: 
          - switch.power_outlet
          - input_select.poweroutlet_mode
        value_template: >
          {{ is_state('switch.power_outlet', 'on') }}
        availability_template: >
          {{ not is_state('switch.power_outlet', 'unavailable') }}
        icon_template: >
          {% if is_state('input_select.poweroutlet_mode', 'Halloween Decorations') %}
            mdi:pumpkin
          {% elif is_state('input_select.poweroutlet_mode', 'Christmas Decorations') %}
            mdi:pine-tree
          {% elif is_state('input_select.poweroutlet_mode', 'Fountain') %}
            mdi:fountain
          {% elif is_state('input_select.poweroutlet_mode', '24/7') %}
            mdi:power-plug
          {% else %}
            mdi:power-plug-off
          {% endif %}
          
  - platform: template
    sensors:
      lamppost_status:
        friendly_name: Lamp Post
        entity_id: 
          - switch.lamp_post
          - input_select.lamppost_mode
        value_template: >
          {{ is_state('switch.lamp_post', 'on') }}
        availability_template: >
          {{ not is_state('switch.lamp_post', 'unavailable') }}
        icon_template: >
          {% if is_state('input_select.lamppost_mode', 'Force Off') %}
            mdi:lightbulb-off
          {% else %}
            mdi:lightbulb
          {% endif %}
          