####################################################
# BINARY SENSORS - POOL                            #
####################################################

  - platform: modbus
    scan_interval: 5
    coils:
      - name: Pool Level High
        hub: !secret modbus1_name
        slave: 1
        coil: 3
        
      - name: Pool Level Low
        hub: !secret modbus1_name
        slave: 1
        coil: 4
        
  - platform: template
    sensors:
      poolpump_status:
        friendly_name: "Pool Pump"
        entity_id:
          - switch.pool_pump
        value_template: >-
          {{ is_state("switch.pool_pump", "on") }}
        icon_template: >-
          mdi:debug-step-over