####################################################
# DEVICES TRACKER                                  #
####################################################
   
  - platform: ping
    count: 2
    hosts:
      jgau_pc_presence: !secret ip_jgau_pc
      cfor_pc_presence: !secret ip_cfor_pc