####################################################
# GROUPS                                           #
####################################################
      
  pool_clock_settings:
    name: Pool Clock Settings
    entities:
      - input_text.pool_text_top
      - input_text.pool_text_bottom
      - input_number.pool_clock_scroll_speed
      
  all_locks:
    name: Lock All
    entities:
      - lock.house_fd_lock
      - lock.house_sd_lock
      - lock.house_bd_lock
      - lock.garage_fd_lock

  locks:
    name: Locks
    entities:
      - input_boolean.house_fd_lock
      - input_boolean.house_fd_unlock
      - input_boolean.house_sd_lock
      - input_boolean.house_sd_unlock
      - input_boolean.house_bd_lock
      - input_boolean.house_bd_unlock
      - input_boolean.garage_fd_lock
      - input_boolean.garage_fd_unlock
      - input_boolean.lock_all
      
  garagedoors:
    name: Garage Doors
    entities:
      - input_boolean.garage_cd_trigger
      
  cars:
    name: Cars
    entities:
      - input_boolean.cars_lexus_lock
      - input_boolean.cars_lexus_unlock
      - input_boolean.cars_lexus_start
      - input_boolean.cars_lexus_other1
      - input_boolean.cars_journey_lock
      - input_boolean.cars_journey_unlock
      - input_boolean.cars_journey_start
      
