####################################################
# RECORDER                                         #
####################################################

#  db_url: !secret db_mysql
#  purge_keep_days: 365
#  db_url: mysql://homeassistant:test1234@core-mariadb/homeassistant?charset=utf8
  purge_keep_days: 5
  purge_interval: 1
  exclude:
    domains:
      - automation
      - binary_sensor
      - calendar
      - camera
      - counter
      - cover
      - date_countdown
      - device_tracker
      - fan
      - group
      - input_select
      - input_text
      - input_boolean
      - input_datetime
      - input_number
      - media_player
      - script
      - sensor
      - sun
      - switch
      - updater
      - zone
    entities:
      - sensor.date
      - sensor.dates
      - sensor.time
      - sensor.times
      - sensor.date_time
      - sensor.time_date
  include:
    entities:
      - device_tracker.life360_cindy
      - device_tracker.life360_jean
      - sensor.controlroom_box_humidity
      - sensor.controlroom_box_temperature
      - sensor.server_cpu_used
      - sensor.server_cpu_temperature_temp
      - sensor.server_mb_temperature_temp
      - sensor.server_ram_used_percent
      - sensor.server_swap_used_percent
      - sensor.load_1m
      - sensor.server_cpu_load
      - sensor.server_used_percent
      - sensor.network_throughput_in_eth0
      - sensor.network_throughput_out_eth0
      - sensor.garage_cd_status
      - sensor.garage_fd_status
      - sensor.house_fd_status
      - sensor.iphone_de_cindy_battery_level
      - sensor.iphone_de_cindy_battery_state
      - sensor.iphone_de_jean_battery_level
      - sensor.iphone_de_jean_battery_state
      - sensor.moon_phases
      - sensor.outdoor_dewpoint
      - sensor.outdoor_feelslike
      - sensor.outdoor_heatindex
      - sensor.outdoor_humidex
      - sensor.outdoor_humidity
      - sensor.outdoor_pressure
      - sensor.outdoor_temperature
      - sensor.outdoor_uv_sensor
      - sensor.outdoor_windchill
      - sensor.postal_battery
      - sensor.postal_new
      - sensor.postal_status
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - sensor.ted5000_mtu1_power
      - sensor.ted5000_mtu1_voltage
      - sensor.ted5000_mtu2_power
      - sensor.ted5000_mtu2_voltage
      - sensor.ted5000_mtu3_power
      - sensor.ted5000_mtu3_voltage
      - sensor.main_power_usage
      - sensor.garage_power_usage
      - sensor.pool_power_usage
      - sensor.main_daily_energy
      - sensor.main_monthly_energy
      - sensor.garage_daily_energy
      - sensor.garage_monthly_energy
      - sensor.pool_daily_energy
      - sensor.pool_monthly_energy
      - sensor.tendency
      - sensor.water_valve_status
      - sensor.weather_control_box_humidity
      - sensor.weather_control_box_temperature
      - sensor.wind_compass
      - sensor.wind_direction
      - sensor.wind_speed
      - sensor.worldwide_coronavirus_confirmed
      - sensor.worldwide_coronavirus_current
      - sensor.worldwide_coronavirus_deaths
      - sensor.worldwide_coronavirus_recovered
      - sensor.canada_coronavirus_confirmed
      - sensor.canada_coronavirus_current
      - sensor.canada_coronavirus_deaths
      - sensor.canada_coronavirus_recovered
      - sensor.master_bed_presence
      - sensor.master_bed_raw
      - switch.pool_filler_valve
      - switch.stepper_wall_clock
      - binary_sensor.lamppost_status
      - binary_sensor.poweroutlet_status
      - binary_sensor.garagefrontlight_status
      - binary_sensor.garagefrontpower_status
      - binary_sensor.house_fd_bell
      - binary_sensor.house_sd_bell
      - binary_sensor.house_bd_bell
      - binary_sensor.garage_fd_bell
      