####################################################
# INPUTS BOOLEAN                                   #
####################################################

  restart_hass:
    name: Restart HASS
    initial: off
    icon: mdi:autorenew
    
  request_position:
    name: Request IOS positions
    initial: off
    icon: mdi:map-marker-radius

  outdoor_rain_trigger:
    name: Outdoor Rain Trigger
