####################################################
# SENSORS - ANNIVERSARIES                          #
####################################################

  - platform: date_countdown
    name: "Cody Counter"
    date: "11-01-2037 20:22"
    
  - platform: date_countdown
    name: "Jean"
    date: "01-04-2020 17:00"
    
  - platform: template
    sensors:
      party_18_ans_cody:
        entity_id: sensor.refresh_1m
        friendly_name: "18 ans de Cody :)"
        unit_of_measurement: 'days'
        value_template: >
          {% set day = states.sensor.cody_counter.attributes.days|int %}
          {% if day > 365 %}
            {{ states.sensor.cody_counter.attributes.days }}
          {% else %}
            {{ states.sensor.cody_counter.state }}
          {% endif %}
        icon_template: >
          mdi:cake-variant
      voyage_floride:
        entity_id: sensor.refresh_1m
        friendly_name: COVID-19 Quarantine - Jean
        value_template: >
          {{ states.sensor.quarantine_jean.state }}
        icon_template: >
          mdi:medical-bag
          
#Famille immédiate
  - platform: anniversaries
    name: Jean's Birthday
    date: '1985-06-27'
  - platform: anniversaries
    name: Cindy's Birthday
    date: '1986-09-08'
  - platform: anniversaries
    name: Cody's Birthday
    date: '2019-01-11'
    
#Pitousseries
  - platform: anniversaries
    name: Mi-Loup's Birthday
    date: '2013-03-14'

#Famille à Jean
  - platform: anniversaries
    name: Michel's Birthday
    date: '1958-04-25'
  - platform: anniversaries
    name: Suzanne's Birthday
    date: '1961-11-23'
    
  - platform: anniversaries
    name: Benoit's Birthday
    date: '1987-02-20'

#Famille à Cindy
  - platform: anniversaries
    name: Gisèle's Birthday
    date: '1953-09-08'

  - platform: anniversaries
    name: Roxanne's Birthday
    date: '1985-10-11'
  - platform: anniversaries
    name: Pierre-Luc's Birthday
    date: '1981-03-07'
  - platform: anniversaries
    name: Kaleb's Birthday
    date: '2018-07-21'

  - platform: anniversaries
    name: Sabrina's Birthday
    date: '1982-02-23'
  - platform: anniversaries
    name: Frédérick's Birthday
    date: '2006-04-19'
    