####################################################
# SENSORS - CONTROL ROOM                           #
####################################################
      
  - platform: mqtt
    name: "ControlRoom Box Temperature"
    state_topic: "Home/Control/Json"
    unit_of_measurement: '째C'
    value_template: "{{ value_json.temp_in }}"
    availability_topic: "Home/Control/LWT"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Home/Control/Json"
    
  - platform: mqtt
    name: "ControlRoom Box Humidity"
    icon: mdi:water-percent
    state_topic: "Home/Control/Json"
    unit_of_measurement: '%'
    value_template: "{{ value_json.hum_in }}"
    availability_topic: "Home/Control/LWT"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Home/Control/Json"
    
  - platform: mqtt
    name: "Cold Storage Temperature"
    state_topic: "Home/Control/Json"
    unit_of_measurement: '째C'
    value_template: "{{ value_json.temp_out }}"
    availability_topic: "Home/Control/LWT"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Home/Control/Json"
    
  - platform: mqtt
    name: "Cold Storage Humidity"
    icon: mdi:water-percent
    state_topic: "Home/Control/Json"
    unit_of_measurement: '%'
    value_template: "{{ value_json.hum_out }}"
    availability_topic: "Home/Control/LWT"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Home/Control/Json"

  - platform: template
    sensors:
      water_valve_status:
        friendly_name: "Water Valve Status"
        value_template: >
          {% if (states.binary_sensor.water_valve_opened.state == 'off') and (states.binary_sensor.water_valve_closed.state == 'on') %}
            Opened
          {% elif (states.binary_sensor.water_valve_closed.state == 'off') and (states.binary_sensor.water_valve_opened.state == 'on') %}
            Closed
          {% else %}
            Unknown
          {% endif %}
        icon_template: >
          {% if (states.binary_sensor.water_valve_opened.state == 'off') and (states.binary_sensor.water_valve_closed.state == 'on') %}
            mdi:pipe
          {% elif (states.binary_sensor.water_valve_closed.state == 'off') and (states.binary_sensor.water_valve_opened.state == 'on') %}
            mdi:pipe-disconnected
          {% else %}
            mdi:help
          {% endif %}
        attribute_templates:
          opened: >
            {% if is_state('binary_sensor.water_valve_opened', "off") %}
              on
            {% else %}
              off
            {% endif %}
          closed: >
            {% if is_state('binary_sensor.water_valve_closed', "off") %}
              on
            {% else %}
              off
            {% endif %}
    
  - platform: template
    sensors:
      water_heater_temperature:
        friendly_name: "Water Heater Temperature"
        value_template: "{{ state_attr('switch.water_heater', 'temp_out') | int }}"
        availability_template: >
          {{ not is_state('switch.water_heater', 'unavailable') }}
        unit_of_measurement: '째C'
        icon_template: mdi:thermometer
      
      water_heater_flow:
        friendly_name: "Water Heater Flow"
        value_template: "{{ state_attr('switch.water_heater', 'flow') | int }}"
        availability_template: >
          {{ not is_state('switch.water_heater', 'unavailable') }}
        unit_of_measurement: 'l/min'
        icon_template: mdi:water-pump
      
      water_heater_status:
        friendly_name: "Water Heater Status"
        value_template: >
          {% if is_state('switch.water_heater', 'off') %}
            Off
          {% elif is_state('switch.water_heater', 'on') and is_state('binary_sensor.water_heater_flow', 'on') %}
           Heating - {{ states('sensor.water_heater_temperature') }}째C
          {% else %}
            Ready
          {% endif %}
        availability_template: >
          {{ not is_state('switch.water_heater', 'unavailable') }}
        icon_template: >
          {% if is_state('switch.water_heater', 'off') %}
            mdi:radiator-off
          {% elif is_state('switch.water_heater', 'on') and is_state('binary_sensor.water_heater_flow', 'on') %}
            mdi:radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}
        attribute_templates:
          temp_in: "{{ state_attr('switch.water_heater', 'temp_in') }}"
          temp_out: "{{ state_attr('switch.water_heater', 'temp_out') }}"
          flow: "{{ state_attr('switch.water_heater', 'flow') }}"
          wifi_rssi: "{{ state_attr('switch.water_heater', 'wifi_rssi') }}"
          wifi_percent: "{{ state_attr('switch.water_heater', 'wifi_percent') }}"
          