####################################################
# SENSORS - HA                                     #
####################################################

  #https://www.home-assistant.io/integrations/glances/
  
  #Home Assistant uptime
  - platform: uptime
    name: Time Online
    unit_of_measurement: hours

  #HA version
  - platform: version
    name: HA Installed Version
    
  - platform: command_line
    name: HA Latest Version
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    scan_interval: 3600
    
#https://wiki.archlinux.org/index.php/APC_UPS
#Do a "apcaccess status" without quotes and use what's available there...
  - platform: apcupsd
    resources:
      - apc
      - date
      - hostname
      - version
      - upsname
      - cable
      - starttime
      - model
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft
      - mbattchg
      - mintimel
      - maxtime
      - lotrans
      - hitrans
      - battv
      - lastxfer
      - numxfers
      - tonbatt
      - cumonbatt
      - xoffbatt
      - battdate
      - nominv
      - nombattv
      - nompower
    
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
    
  #Terminal command for network card name: ifconfig
  - platform: systemmonitor
    resources:
    # - type: processor_use
    # - type: disk_use_percent
      # arg: /
    # - type: memory_use_percent
    #- type: swap_use_percent
    - type: last_boot
    - type: load_1m
    - type: load_15m
    #IoT card
    - type: packets_in
      arg: hassio
    - type: packets_out
      arg: hassio
    - type: throughput_network_in
      arg: hassio
    - type: throughput_network_out
      arg: hassio
    - type: network_in
      arg: hassio
    - type: network_out
      arg: hassio
    #Internet card
    - type: packets_in
      arg: enp1s6
    - type: packets_out
      arg: enp1s6
    - type: throughput_network_in
      arg: enp1s6
    - type: throughput_network_out
      arg: enp1s6
    - type: network_in
      arg: enp1s6
    - type: network_out
      arg: enp1s6
