####################################################
# SENSORS - MOON                                   #
####################################################

  - platform: moon
  
  - platform: template
    sensors:
      moon_phases:
        friendly_name: 'Moon Phases'
        value_template: >
          {{ states('sensor.moon').replace('_',' ') | title }}
        entity_picture_template: >
          {% set state = states('sensor.moon').title().replace('_','').replace(' ','') %}
          {{ '/local/images/MoonPhases/N{}.jpg'.format(state) }}