###################################################
# AUTOMATIONS - NOTIFICATIONS                     #
###################################################

  - alias: HA Update Notification
    mode: restart
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: binary_sensor.ha_update_available
        from: 'off'
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.ha_update_available
          state: 'on'
        - condition: state
          entity_id: binary_sensor.updater
          state: 'on'
    action:
      - service: script.haupdateavailable

#   - alias: Publish Florida Days
#     mode: restart
#     trigger:
#       - platform: time
#         at: '09:00:00'
#     action:
#       - service: notify.ios_notify_parents
#         data:
#           title: "Voyage en Floride :D"
#           message: "Décollage dans: {{ states.sensor.voyage_floride_counter.attributes.days }} {% if states.sensor.voyage_floride_counter.attributes.days > 1 %}jours{% else %}jour{% endif %}!"
#       - service: notify.ios_notify_parents
#         data:
#           message: clear_badge
          
  - alias: Publish Postal Arrival
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.postal_status
        from: 'No Mail'
        to: 'New Mail'
        for: '00:00:30'
    # condition:
    #   - condition: template
    #     value_template: "{{ is_state_attr('sensor.postal_status', 'source', 'sender') }}"
    action:
      - service: input_datetime.set_datetime
        data_template:
          entity_id: input_datetime.last_postal_arrival
          time: '{{ (as_timestamp(now()) | timestamp_custom("%H:%M:%S", true)) }}'
          date: '{{ (as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true)) }}'
      - service: notify.ios_notify_parents
        data:
          title: "Postal Status Update"
          message: |
            New Mail has been delivered
            id: {{ states.sensor.postal_status.attributes.id }}
            {% if state_attr('sensor.postal_status', 'battery')|int <= 50 %}Critical battery level{% elif state_attr('sensor.postal_status', 'battery')|int <= 90 %}Low battery level{% endif %}
          
  - alias: Publish Postal Removal
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.postal_status
        from: 'New Mail'
        to: 'No Mail'
        for: '00:00:30'
    # condition:
    #   - condition: template
    #     value_template: "{{ is_state_attr('sensor.postal_status', 'source', 'sender') }}"
    action:
      - service: input_datetime.set_datetime
        data_template:
          entity_id: input_datetime.last_postal_removal
          time: '{{ (as_timestamp(now()) | timestamp_custom("%H:%M:%S", true)) }}'
          date: '{{ (as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true)) }}'
      - service: notify.ios_notify_parents
        data:
          title: "Postal Status Update"
          message: |
            Mail has been removed
            id: {{ states.sensor.postal_status.attributes.id }}
            {% if state_attr('sensor.postal_status', 'battery')|int <= 50 %}Critical battery level{% elif state_attr('sensor.postal_status', 'battery')|int <= 90 %}Low battery level{% endif %}
          
  - alias: Lexus Office Start Reminder
    mode: restart
    trigger:
      - platform: time
        at: '11:45:00'
      - platform: time
        at: '16:45:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.life360_jean
          state: 'DO2 Contrôle'
        - condition: numeric_state
          entity_id: sensor.outdoor_temperature
          below: 5
    action:
      - service: notify.sms_jean
        data:
          message: "Start the Lexus"

  # - alias: Publish Persistent
    # mode: restart
    # trigger:
      # - platform: time_pattern
        # minutes: '/59'         
    # action:
      # service: persistent_notification.create
      # data:
        # message: "Your message goes here"
        # title: "Custom subject"

  - alias: Publish Collect Notification
    mode: restart
    trigger:
      platform: time
      at: '7:00:00'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.collect_trash_week
          state: 'Today'
        - condition: state
          entity_id: sensor.collect_recycle_week
          state: 'Today'
        - condition: state
          entity_id: sensor.collect_compost_week
          state: 'Today'
    action:
      service_template: >
        {% if is_state('device_tracker.life360_jean', 'home') and is_state('device_tracker.life360_cindy', 'home') %}
          notify.sms_notify_all
        {% elif is_state('device_tracker.life360_jean', 'home') %}
          notify.sms_jean
        {% elif is_state('device_tracker.life360_cindy', 'home') %}
          notify.sms_cindy
        {% else %}
          notify.sms_jean
        {% endif %}
      data_template:
        title: "Collect day"
        message: >
          {% if is_state('sensor.collect_trash_week', 'Today') and is_state('sensor.collect_recycle_week', 'Today') and is_state('sensor.collect_compost_week', 'Today') and state_attr('sensor.dates', 'dayofyear')|int >= 300 %}
            Put TRASH, RECYCLE & COMPOST out for collection today
          {% elif is_state('sensor.collect_trash_week', 'Today') and is_state('sensor.collect_recycle_week', 'Today') %}
            Put TRASH & RECYCLE out for collection today
          {% elif is_state('sensor.collect_recycle_week', 'Today') and is_state('sensor.collect_compost_week', 'Today') and state_attr('sensor.dates', 'dayofyear')|int >= 300 %}
            Put RECYCLE & COMPOST out for collection today
          {% elif is_state('sensor.collect_trash_week', 'Today') and is_state('sensor.collect_compost_week', 'Today') and state_attr('sensor.dates', 'dayofyear')|int >= 300 %}
            Put TRASH & COMPOST out for collection today
          {% elif is_state('sensor.collect_trash_week', 'Today') %}
            Put TRASH out for collection today
          {% elif is_state('sensor.collect_recycle_week', 'Today') %}
            Put RECYCLE out for collection today
          {% elif is_state('sensor.collect_compost_week', 'Today') and state_attr('sensor.dates', 'dayofyear')|int >= 300 %}
            Put COMPOST out for collection today
          {% endif %}

  - alias: Printer3D Job Complete
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing
        from: 'on'
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.octoprint_printing_error
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.master_bed_raw
        below: 100
    action:
      - service: notify.sms_jean
        data:
          message: "3D Printing Completed"
          
  - alias: Printer3D Job Failed
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.octoprint_printing_error
        from: 'off'
        to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.master_bed_raw
        below: 100
    action:
      - service: notify.sms_jean
        data:
          message: "3D Printing Failed"
          
#   - alias: Set new dates for collects
#     mode: restart
#     trigger:
#       platform: time
#       at: "01:00:00"
#     condition:
#       - condition: template
#         value_template: '{{ now().date()|string == "2020-09-23" }}'
#     action:
#       - service: input_select.select_option
#         data:
#           entity_id: input_select.collect_trash
#           option: Odd/Wednesday
#       - service: input_select.select_option
#         data:
#           entity_id: input_select.collect_recycle
#           option: Even/Wednesday
          