###################################################
# AUTOMATIONS - POOL                              #
###################################################

  #Spring mode, runs pump all day, stop 4h, run 4h, stop 4h, run 12h
  #Summer mode, runs pump based on day of week (runs longer on fridays/saturdays)
  #Autumn mode, pump not running on peak hours
  #If temperature below 5°C, run pump
  #Pool water level has to be above low level since 2 minutes
  - alias: Pool Pump Control
    initial_state: true
    trigger:
      - platform: time_pattern
        seconds: '/5'
      - platform: state
        entity_id: input_select.poolpump_mode
    action:
      entity_id: switch.pool_pump
      service_template: >
        {% set curHour = now().hour %}
        {% set curWeekday = now().weekday() %}
        {% set PP = false %}
        
        {% if is_state('input_select.poolpump_mode', '24/7') %}
          {% set PP = true %}
        {% elif is_state('input_select.poolpump_mode', 'Spring') %}
          {% if curHour >= 8 and curHour < 20 %}
            {% set PP = true %}
          {% elif curHour >= 0 and curHour < 24 %}
            {% set PP = true %}
          {% endif %}
        {% elif is_state('input_select.poolpump_mode', 'Summer') %}
          {% if curWeekday in (0,1,2,3,6) %}
            {% if curHour >= 6 and curHour < 18 %}
              {% set PP = true %}
            {% elif curHour >= 22 or curHour < 2 %}
              {% set PP = true %}
            {% endif %}
          {% else %}
            {% if curHour >= 6 and curHour < 23 %}
              {% set PP = true %}
            {% elif curHour >= 1 or curHour < 4 %}
              {% set PP = true %}
            {% endif %}
          {% endif %}
        {% elif is_state('input_select.poolpump_mode', 'Autumn') %}
          {% if curHour >= 2 and curHour < 6 %}
            {% set PP = true %}
          {% elif curHour >= 9 and curHour < 11 %}
            {% set PP = true %}
          {% elif curHour >= 14 and curHour < 16 %}
            {% set PP = true %}
          {% elif curHour >= 21 and curHour < 23 %}
            {% set PP = true %}
          {% endif %}
        {% endif %}
        
        {% if not is_state('input_select.poolpump_mode', 'Winter/Off') and states.sensor.outdoor_temperature.state|float < 5.0 %}
          {% set PP = true %}
        {% endif %}
        
        {% set lastLevel = as_timestamp(now()) - as_timestamp(states.binary_sensor.pool_level_low.last_changed) %}
        {% if is_state('binary_sensor.pool_level_low', 'off') and lastLevel >= 120 %}
          {% set PP = false %}
        {% endif %}
        
        {% if PP == true %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}

  #Pool water level has to be below high level since 2 minutes
  #Pool pump mode shall not be in Winter mode
  #Filler valve can't operate more than 1h/day
  - alias: Pool Filler Control
    initial_state: true
    trigger:
      - platform: time_pattern
        seconds: '/5'
    action:
      entity_id: switch.pool_filler_valve
      service_template: >
        {% set lastLevel = as_timestamp(now()) - as_timestamp(states.binary_sensor.pool_level_high.last_changed) %}
        {% set PF = false %}
        
        {% if lastLevel >= 120 %}
          {% if is_state('binary_sensor.pool_level_high', 'off') %}
            {% set PF = true %}
          {% elif is_state('binary_sensor.pool_level_high', 'on') %}
            {% set PF = false %}
          {% endif %}
        {% endif %}
        
        {% if states.sensor.pool_filler_timer.state|float >= 1.0 %}
          {% set PF = false %}
        {% elif is_state('input_select.poolpump_mode', 'Winter/Off') %}
          {% set PF = false %}
        {% endif %}
                
        {% if PF == true %}
          switch.turn_on
        {% else %}
          switch.turn_off
        {% endif %}
        
  - alias: "Pool Drain Adjust"
    initial_state: true
    trigger:
      platform: state
      entity_id: input_number.pool_drain_percent
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Control/Cmd"
        payload: '{"drain":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false
        
  - alias: "Pool Slide Adjust"
    initial_state: true
    trigger:
      platform: state
      entity_id: input_number.pool_slide_percent
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Control/Cmd"
        payload: '{"slide":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false
        
  - alias: "Pool Heatpump Adjust"
    initial_state: true
    trigger:
      platform: state
      entity_id: input_number.pool_heatpump_percent
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Control/Cmd"
        payload: '{"heatp":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false
        
######## POOL CLOCK ########
        
  #Input Text Changes Trigger
  - alias: Pool Top Text Change
    trigger:
      platform: state
      entity_id: input_text.pool_text_top
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Clock/Cmd"
        payload: '{"uptxt":"{{ trigger.to_state.state }}"}'
        qos: 0
        retain: false
        
  - alias: Pool Bottom Text Change
    initial_state: true
    trigger:
      platform: state
      entity_id: input_text.pool_text_bottom
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Clock/Cmd"
        payload: '{"dntxt":"{{ trigger.to_state.state }}"}'
        qos: 0
        retain: false

  - alias: "Pool Clock Scroll Speed"
    initial_state: true
    trigger:
      platform: state
      entity_id: input_number.pool_clock_scroll_speed
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Clock/Cmd"
        payload: '{"scroll":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false
        
  - alias: "Pool Clock Transistion Speed"
    initial_state: true
    trigger:
      platform: state
      entity_id: input_number.pool_clock_trans_speed
    action:
    - service: mqtt.publish
      data_template:
        topic: "Pool/Clock/LED/Cmd"
        payload: '{"transition":{{ trigger.to_state.state | int }}}'
        qos: 0
        retain: false

#Publish data to device every minute or when a device requests an update (boot up or invalid data detected (by the device))
  - alias: Publish Pool Clock Data
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
      - platform: mqtt
        topic: "Home/Global/Time/Request"
        payload: 'ON'
        encoding: 'utf-8'
    action:
      - service: mqtt.publish
        data_template:
          topic: "Pool/Clock/Cmd"
          payload_template: '{"wtemp":"{{states.sensor.pool_temperature.state}}","wph":"{{states.sensor.pool_ph.state}}","otemp":"{{states.sensor.outdoor_temperature.state}}","ohum":"{{states.sensor.outdoor_humidity.state}}"}'
          qos: 0
          retain: false
