##########################################
# CUSTOMIZATIONS - BATTERIES             #
##########################################
  
# STANDARD COLORS
#=========================================
# Icon Online:  var(--state-icon-color) --> #007AFF
# Icon Offline: var(--state-icon-unavailable-color) --> #4F5F78
# Icon Active:  var(--state-icon-active-color) --> #FBCD41
# Red:          FF0000
# Yellow:       FFFF00
# Orange:       FFA500
# Lt Purple:    A500FF
# Dk Purple:    5C005C
# Lt Green:     00FF00
# Gold:         A3852A

  sensor.ups_status:
    templates:
      icon: >
        if (state === 'ONLINE') return 'mdi:power-plug';
        return 'mdi:power-plug-off';
      icon_color: >
        if (state === 'ONLINE') return 'var(--state-icon-active-color)';
        if (state === 'ONBATT') return 'var(--state-icon-color)';
        return 'var(--state-icon-unavailable-color)';
  
  sensor.ups_battery:
    templates:
      icon: >
        if (state >= 99) return 'mdi:battery';
        if (entities['sensor.ups_status'].state === 'ONLINE')
        {
          if (state <= 5) return 'mdi:battery-charging-outline';
          if (state <= 10) return 'mdi:battery-charging-10';
          if (state <= 20) return 'mdi:battery-charging-20';
          if (state <= 30) return 'mdi:battery-charging-30';
          if (state <= 40) return 'mdi:battery-charging-40';
          if (state <= 50) return 'mdi:battery-charging-50';
          if (state <= 60) return 'mdi:battery-charging-60';
          if (state <= 70) return 'mdi:battery-charging-70';
          if (state <= 80) return 'mdi:battery-charging-80';
          if (state <= 90) return 'mdi:battery-charging-90';
          if (state <= 100) return 'mdi:battery-charging-100';
        }
        else
        {
          if (state <= 5) return 'mdi:battery-outline';
          if (state <= 10) return 'mdi:battery-10';
          if (state <= 20) return 'mdi:battery-20';
          if (state <= 30) return 'mdi:battery-30';
          if (state <= 40) return 'mdi:battery-40';
          if (state <= 50) return 'mdi:battery-50';
          if (state <= 60) return 'mdi:battery-60';
          if (state <= 70) return 'mdi:battery-70';
          if (state <= 80) return 'mdi:battery-80';
          if (state <= 90) return 'mdi:battery-90';
          if (state <= 100) return 'mdi:battery-100';
        }
        return 'mdi:battery-unknown';
      icon_color: >
        if (state > 70) return 'var(--label-badge-green)';
        if (state > 45) return 'var(--label-badge-yellow)';
        if (state > 0) return 'var(--label-badge-red)';
        return 'var(--state-icon-unavailable-color)';

