##########################################
# CUSTOMIZATIONS - COMPUTERS             #
##########################################

  binary_sensor.jgau_pc:
    templates:
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        return 'var(--state-icon-color)';

  binary_sensor.cfor_pc:
    templates:
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        return 'var(--state-icon-color)';
        
  binary_sensor.main_router:
    templates:
      icon: >
        if (state === 'on') return 'mdi:access-point-network'; 
        return 'mdi:access-point-network-off';
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        return 'var(--state-icon-color)';
        
  binary_sensor.garage_router:
    templates:
      icon: >
        if (state === 'on') return 'mdi:access-point-network'; 
        return 'mdi:access-point-network-off';
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        return 'var(--state-icon-color)';

  binary_sensor.pool_router:
    templates:
      icon: >
        if (state === 'on') return 'mdi:access-point-network'; 
        return 'mdi:access-point-network-off';
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        return 'var(--state-icon-color)';