##########################################
# CUSTOMIZATIONS - DOORS & LOCKS         #
##########################################

# STANDARD COLORS
#=========================================
# Icon Online:  var(--state-icon-color) --> #007AFF
# Icon Offline: var(--state-icon-unavailable-color) --> #4F5F78
# Icon Active:  var(--state-icon-active-color) --> #FBCD41
# Red:          FF0000
# Yellow:       FFFF00
# Orange:       FFA500
# Lt Purple:    A500FF
# Dk Purple:    5C005C
# Lt Green:     00FF00
# Gold:         A3852A

  input_text.doorlock_passcode:
    custom_ui_state_card: state-card-custom-ui
    icon: mdi:shield-lock
    templates:
      icon_color: >
        if (entities['sensor.lock_passcode_ok'].state === 'on') return 'var(--label-badge-green)';
        return 'var(--state-icon-color)';
  
  input_text.doorlock_passcode_list:
    hidden: true
    
  sensor.house_fd_status:
    custom_ui_state_card: state-card-custom-ui
    templates:
      icon: >
        if (state === 'Ok') return 'mdi:shield-lock';
        if (state === 'Unlocked') return 'mdi:shield-remove';
        if (state === 'Opened') return 'mdi:door-open';
        return 'mdi:close-octagon';
      icon_color: >
        if (state === 'Ok') return 'green';
        if (state === 'Unlocked') return 'red';
        if (state === 'Opened') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'red';
  
  sensor.house_sd_status:
    custom_ui_state_card: state-card-custom-ui
    templates:
      icon: >
        if (state === 'Ok') return 'mdi:shield-lock';
        if (state === 'Unlocked') return 'mdi:shield-remove';
        if (state === 'Opened') return 'mdi:door-open';
        return 'mdi:close-octagon';
      icon_color: >
        if (state === 'Unavailable') return 'var(--state-icon-unavailable-color)';
        if (state === 'Ok') return 'green';
        if (state === 'Unlocked') return 'red';
        if (state === 'Opened') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'red';
  
  sensor.house_bd_status:
    custom_ui_state_card: state-card-custom-ui
    templates:
      icon: >
        if (state === 'Ok') return 'mdi:shield-lock';
        if (state === 'Unlocked') return 'mdi:shield-remove';
        if (state === 'Opened') return 'mdi:door-open';
        return 'mdi:close-octagon';
      icon_color: >
        if (state === 'Ok') return 'green';
        if (state === 'Unlocked') return 'red';
        if (state === 'Opened') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'red';

  sensor.garage_fd_status:
    custom_ui_state_card: state-card-custom-ui
    templates:
      icon: >
        if (state === 'Ok') return 'mdi:shield-lock';
        if (state === 'Unlocked') return 'mdi:shield-remove';
        if (state === 'Opened') return 'mdi:door-open';
        return 'mdi:close-octagon';
      icon_color: >
        if (state === 'Ok') return 'green';
        if (state === 'Unlocked') return 'red';
        if (state === 'Opened') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'red';

  sensor.garage_cd_status:
    custom_ui_state_card: state-card-custom-ui
    templates:
      icon: >
        if (state === 'Ok') return 'mdi:shield-lock';
        if (state === 'Fully Opened') return 'mdi:garage-open';
        if (state === 'Opened') return 'mdi:garage-alert';
        return 'mdi:close-octagon';
      icon_color: >
        if (state === 'Ok') return 'green';
        if (state === 'Fully Opened') return 'var(--state-icon-active-color)';
        if (state === 'Opened') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'red';
