##########################################
# CUSTOMIZATIONS - POOL                  #
##########################################

  #Include other files
  #!include_dir_merge_named Customize
  
  
##########################################
# STANDARD COLORS                        #
##########################################
# Icon Online:  2F7EFD
# Icon Offline: 48485E
# Icon Active:  FBCD41
# Red:          FF0000
# Yellow:       FFFF00
# Orange:       FFA500
# Lt Purple:    A500FF
# Dk Purple:    5C005C
    
  input_select.poolpump_mode:
    icon: mdi:power-plug-off
    templates:
      icon: >
        if (state === 'Spring') return 'mdi:flower-tulip';
        if (state === 'Summer') return 'mdi:weather-sunny';
        if (state === 'Autumn') return 'mdi:leaf-maple';
        if (state === '24/7') return 'mdi:clock-start';
        if (state === 'Winter/Off') return 'mdi:power-off';
        return 'mdi:power-plug-off';
        
  binary_sensor.poolpump_status:
    icon: mdi:debug-step-over
    #icon: mdi:pump
    templates:
      icon_color: >
        if (state === 'on') return '#FBCD41';
        if (state === 'unavailable') return '#48485E';
        return '#2F7EFD';
    
  switch.pool_pump:
    icon: mdi:debug-step-over
    #icon: mdi:pump
    templates:
      icon_color: >
        if (state === 'on') return '#FBCD41';
        if (state === 'unavailable') return '#48485E';
        return '#2F7EFD';
    
  switch.pool_heat_pump:
    icon: mdi:radiator
    templates:
      icon: >
        if (state === 'on') return 'mdi:radiator';
        return 'mdi:radiator-off';
      icon_color: >
        if (state === 'on') return '#FBCD41';
        if (state === 'unavailable') return '#48485E';
        return '#2F7EFD';
  
  binary_sensor.poolfiller_status:
    icon: mdi:debug-step-out
    templates:
      icon_color: >
        if (state === 'on') return '#FBCD41';
        if (state === 'unavailable') return '#48485E';
        return '#2F7EFD';
        
  switch.pool_filler_valve:
    icon: mdi:debug-step-out
    templates:
      icon_color: >
        if (state === 'on') return '#FBCD41';
        if (state === 'unavailable') return '#48485E';
        return '#2F7EFD';
  
  switch.pond_pump:
    icon: mdi:fish
    templates:
      icon_color: >
        if (state === 'on') return '#FBCD41';
        if (state === 'unavailable') return '#48485E';
        return '#2F7EFD';
        
  switch.garden_watering:
    icon: mdi:water
    templates:
      icon_color: >
        if (state === 'on') return '#FBCD41';
        if (state === 'unavailable') return '#48485E';
        return '#2F7EFD';
        