####################################################
# INPUT SELECT - POOL                              #
####################################################

  pool_clock_time_color:
    name: Time Display Color
    icon: mdi:clock
    options:
      - Red
      - Green
      - Blue
      - Scroll
    initial: Red

  poolpump_mode:
    name: Pool Pump Mode
    icon: mdi:calendar-clock
    options:
      - Winter/Off
      - Spring
      - Summer
      - Autumn
      - 24/7
      
  poolheat_mode:
    name: Pool Heater Mode
    icon: mdi:calendar-clock
    options:
      - Winter/Off
      - Auto
      - 24/7
      
  poolfiller_mode:
    name: Pool Filler Mode
    icon: mdi:calendar-clock
    options:
      - Winter/Off
      - Auto
      - Manual
      