##########################################
# GLOBAL CUSTOMIZATIONS - BINARY SENSORS #
##########################################

#   binary_sensor.*:
#     #state_color: true
#     hide_attributes:
#       - templates
#       - icon_color
    # templates:
    #   icon_color: >
    #     if (state === 'on') return 'var(--state-icon-active-color)';
    #     if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
    #     return 'var(--state-icon-color)';
        
  binary_sensor.*_router:
    templates:
      icon: >
        if (state === 'on') return 'mdi:access-point-network'; 
        return 'mdi:access-point-network-off';
      icon_color: >
        if (state === 'on') return 'var(--state-icon-active-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'var(--state-icon-color)';
        
#   binary_sensor.*_pc:
#     templates:
#       icon_color: >
        # if (state === 'on') return 'var(--state-icon-active-color)';
        # if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        # return 'var(--state-icon-color)';