switch:
  - platform: mqtt
    name: Water Heater
    state_topic: "Home/WaterHeater/Stts"
    command_topic: "Home/WaterHeater/Cmd"
    value_template: '{{ value_json.state }}'
    availability_topic: "Home/WaterHeater/LWT"
    payload_on: '{"state":"ON"}'
    payload_off: '{"state":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Home/WaterHeater/Json"

sensor:
  - platform: template
    sensors:
      water_heater_temperature:
        friendly_name: "Water Heater Temperature"
        value_template: "{{ state_attr('switch.water_heater', 'temp_out') | int }}"
        availability_template: >
          {{ not is_state('switch.water_heater', 'unavailable') }}
        unit_of_measurement: '°C'
        icon_template: mdi:thermometer
      
      water_heater_flow:
        friendly_name: "Water Heater Flow"
        value_template: "{{ state_attr('switch.water_heater', 'flow') | int }}"
        availability_template: >
          {{ not is_state('switch.water_heater', 'unavailable') }}
        unit_of_measurement: 'l/min'
        icon_template: mdi:water-pump
      
      water_heater_status:
        friendly_name: "Water Heater Status"
        value_template: >
          {% if is_state('switch.water_heater', 'off') %}
            Off
          {% elif is_state('switch.water_heater', 'on') and is_state('binary_sensor.water_heater_flow', 'on') %}
           Heating - {{ states('sensor.water_heater_temperature') }}°C
          {% else %}
            Ready
          {% endif %}
        availability_template: >
          {{ not is_state('switch.water_heater', 'unavailable') }}
        icon_template: >
          {% if is_state('switch.water_heater', 'off') %}
            mdi:radiator-off
          {% elif is_state('switch.water_heater', 'on') and is_state('binary_sensor.water_heater_flow', 'on') %}
            mdi:radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}
        attribute_templates:
          temp_in: "{{ state_attr('switch.water_heater', 'temp_in') }}"
          temp_out: "{{ state_attr('switch.water_heater', 'temp_out') }}"
          flow: "{{ state_attr('switch.water_heater', 'flow') }}"
          wifi_rssi: "{{ state_attr('switch.water_heater', 'wifi_rssi') }}"
          wifi_percent: "{{ state_attr('switch.water_heater', 'wifi_percent') }}"

binary_sensor:
  - platform: template
    sensors:
      water_heater_flow:
        friendly_name: Water Heater Flow
        entity_id: 
          - sensor.water_heater_status
          - sensor.water_heater_temperature
          - sensor.water_heater_flow
        value_template: >
          {{ state_attr('sensor.water_heater_status', 'flow')|int > 1 }}
        availability_template: >
          {{ not is_state('switch.water_heater', 'unavailable') }}
        icon_template: >
          {% if is_state('switch.water_heater', 'off') %}
            mdi:radiator-off
          {% elif state_attr('switch.water_heater', 'flow')|int > 1 %}
            mdi-radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}

customize:
  sensor.water_heater_status:
    templates:
      icon_color: >
        if (state === 'Ready') return 'var(--state-icon-color)';
        if (state === 'Off') return 'var(--state-icon-color)';
        if (state === 'unavailable') return 'var(--state-icon-unavailable-color)';
        return 'var(--state-icon-active-color)';

views:
- title: Parameters
  icon: mdi:wrench
  # Unique path for direct access /lovelace/${path}
  path: params
  visible: true
  cards:
    - type: entities
      title: Water Entrance
      show_header_toggle: false
      entities:
        - type: custom:fold-entity-row
          head: sensor.water_heater_status
          entities:
            - switch.water_heater
            - sensor.water_heater_temperature
            - sensor.water_heater_flow