####################################################
# SWITCHES - CONTROL ROOM                          #
####################################################

  #Outdoor Relay
  - platform: mqtt
    name: Lamp Post
    state_topic: "Home/Control/Relay/Stts"
    command_topic: "Home/Control/Relay/Cmd"
    value_template: '{{ value_json.r9 }}'
    availability_topic: "Home/Control/LWT"
    payload_on: '{"r9":"ON"}'
    payload_off: '{"r9":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
  
  #Outdoor Relay
  - platform: mqtt
    name: Power Outlet
    state_topic: "Home/Control/Relay/Stts"
    command_topic: "Home/Control/Relay/Cmd"
    value_template: '{{ value_json.r10 }}'
    availability_topic: "Home/Control/LWT"
    payload_on: '{"r10":"ON"}'
    payload_off: '{"r10":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    
  - platform: mqtt
    name: Backyard Irrigation
    state_topic: "Home/Control/Relay/Stts"
    command_topic: "Home/Control/Relay/Cmd"
    value_template: '{{ value_json.r2 }}'
    availability_topic: "Home/Control/LWT"
    payload_on: '{"r2":"ON"}'
    payload_off: '{"r2":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    
  - platform: mqtt
    name: Frontyard Irrigation
    state_topic: "Home/Control/Relay/Stts"
    command_topic: "Home/Control/Relay/Cmd"
    value_template: '{{ value_json.r3 }}'
    availability_topic: "Home/Control/LWT"
    payload_on: '{"r3":"ON"}'
    payload_off: '{"r3":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    
  - platform: mqtt
    name: Water Valve Close
    icon: mdi:pipe-disconnected
    state_topic: "Home/Control/Relay/Stts"
    command_topic: "Home/Control/Relay/Cmd"
    value_template: '{{ value_json.r7 }}'
    availability_topic: "Home/Control/LWT"
    payload_on: '{"r7":"ON"}'
    payload_off: '{"r7":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    
  - platform: mqtt
    name: Water Valve Open
    icon: mdi:pipe
    state_topic: "Home/Control/Relay/Stts"
    command_topic: "Home/Control/Relay/Cmd"
    value_template: '{{ value_json.r8 }}'
    availability_topic: "Home/Control/LWT"
    payload_on: '{"r8":"ON"}'
    payload_off: '{"r8":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Home/Control/Json"
    
  - platform: mqtt
    name: Water Heater
    state_topic: "Home/WaterHeater/Stts"
    command_topic: "Home/WaterHeater/Cmd"
    value_template: '{{ value_json.state }}'
    availability_topic: "Home/WaterHeater/LWT"
    payload_on: '{"state":"ON"}'
    payload_off: '{"state":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Home/WaterHeater/Json"
    