####################################################
# SWITCHES - GARAGE                                #
####################################################

  - platform: mqtt
    name: Garage Front Light
    state_topic: "Garage/Lights/Relay/Stts"
    command_topic: "Garage/Lights/Relay/Cmd"
    value_template: '{{ value_json.r1 }}'
    availability_topic: "Garage/Lights/LWT"
    payload_on: '{"r1":"ON"}'
    payload_off: '{"r1":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Garage/Lights/Json"
    
  - platform: mqtt
    name: Garage Front Power
    state_topic: "Garage/Lights/Relay/Stts"
    command_topic: "Garage/Lights/Relay/Cmd"
    value_template: '{{ value_json.r2 }}'
    availability_topic: "Garage/Lights/LWT"
    payload_on: '{"r2":"ON"}'
    payload_off: '{"r2":"OFF"}'
    state_on: "ON"
    state_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"
    qos: 0
    json_attributes_topic: "Garage/Lights/Json"
    